services:
  app_blue:
    build: ./app-container
    container_name: app_blue
    restart: always
    expose:
      - "80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: "30s"
      timeout: "5s"
      retries: 3

  app_green:
    build: ./app-container
    container_name: app_green
    restart: always
    expose:
      - "80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: "30s"
      timeout: "5s"
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      app_blue:
        condition: service_healthy
